### ISSUE TITLE
unity 2019.4无法连接调试

### ISSUE THREAD

**Issue by moto2002** [jiangzheng1986/LuaPerfect#12]
Project Directory (Debuggee): G:/svn/lrs_develop/client/src/project_unity_main
Project Directory (Debugger): G:/svn/lrs_develop/client/src/project_unity_main/Assets
Projects are not matched, connection has been rejected.

**Comment by jiangzheng1986** [comment]
你好，已经私聊你的邮箱，我先跟你了解一下具体的情况，感谢关注。。

**Comment by jiangzheng1986** [comment]
已查明是因为改了Unity.exe的名称导致被调试器无法识别成Unity项目，感谢反馈。
