### ISSUE TITLE
File/CreateShortcut 点击没有反应

### ISSUE THREAD

**Issue by CongDeveloper** [jiangzheng1986/LuaPerfect#16]

**Comment by jiangzheng1986** [comment]
你好，File菜单的CreateShortcut功能为在桌面创建快捷键，我测试了一下，在本机是正常的。目前不确定是否由于权限等问题导致。一个可供替代的方案是在操作系统的任务栏的LuaPerfect的图标上点击右键，并在弹出的右键菜单中选择固定到任务栏。

**Comment by CongDeveloper** [comment]
感谢解答，我还以为是编辑快捷键的。如果是创建桌面快捷方式，那功能是正常的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiangzheng1986/LuaPerfect"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月1日(星期三) 下午2:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiangzheng1986/LuaPerfect] File/CreateShortcut 点击没有反应 (Issue #16)





 
你好，File菜单的CreateShortcut功能为在桌面创建快捷键，我测试了一下，在本机是正常的。目前不确定是否由于权限等问题导致。一个可供替代的方案是在操作系统的任务栏的LuaPerfect的图标上点击右键，并在弹出的右键菜单中选择固定到菜单栏。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiangzheng1986** [comment]
快捷键等主题的设置，可以到官方群下载R7 Themes.zip，里面也有快捷键编辑的相关说明。
