### ISSUE TITLE
请问支持中文标识符吗?

### ISSUE THREAD

**Issue by nobodxbodon** [jiangzheng1986/LuaPerfect#2]
之前印象Lua本身不支持Unicode标识符?

**Comment by jiangzheng1986** [comment]
你好，这边有关于Lua的Unicode支持的计划和未发布工作。关于Lua支持Unicode的暂时主要由于不属于LuaPerfect IDE相关，将会后续在其他Repo中进行跟进，感谢issue，谢谢。
