### ISSUE TITLE
1.036版本无法对4个空格进行shift tab

### ISSUE THREAD

**Issue by LostWaym** [jiangzheng1986/LuaPerfect#21]
但是制表符就可以shift tab，所以在使用translate tab to space这个功能的时候就有点不方便，在需要shift tab的情况…
考虑一下增加可以shift tab4个空格的功能吗？

**Comment by jiangzheng1986** [comment]
你好，选中单行时是无法进行shift-tab操作的，这样做是为了保持与Visual Studio一致。




Anders
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiangzheng1986/LuaPerfect"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月7日(星期二) 下午3:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[jiangzheng1986/LuaPerfect] 1.036版本无法对4个空格进行shift tab (Issue #21)





 
但是制表符就可以shift tab，所以在使用translate tab to space这个功能的时候就有点不方便，在需要shift tab的情况…
 考虑一下增加可以shift tab的功能吗？

**Comment by jiangzheng1986** [comment]
一般是选中多行后进行shift-tab操作

**Comment by LostWaym** [comment]
> 

确实如此，感谢你的回复！
